# Generated by Django 6.0.5 on 2026-05-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_role_remove_company_comp_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default='Default Dept', max_length=255),
            preserve_default=False,
        ),
    ]
